### ISSUE TITLE
"Official" Ionic docset

### ISSUE THREAD

**Issue by Kapeli** [DarkSwoop/dash-ionic#2]
Hi @DarkSwoop. This is just a heads-up that a Ionic docset made by me will be released in the next Dash update. Please let me know what you would like to happen with your Ionic docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/Ionic.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by DarkSwoop** [comment]
@Kapeli I was happy to get this docset up and running and I hope it helped others too. Feel free to remove it. Your version of the ionic documentation looks cool but it'll take some time for me to get comfortable with it because the official docs look different (missing html sidebar navigation etc).
